# Site settings
title: Code Carrots JavaScript
email: zuzapodwinska@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Strona informacyjna na temat zajęć z programowania w języku JavaScript w ramach Geek Girls Carrots.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  CodeCarrotsJS

# Build settings
markdown: kramdown
